import { invoke } from "@tauri-apps/api/core";
import type {Activity,AssistantReply,Connection,Dashboard,DiagnosticResult,EventSummary,InstalledApp,NetworkAlert,NetworkConfig,Package,PhysicalDiskHealth,PrinterInfo,Process,Proposal,RuntimeStatus,Security,ServiceInfo,StartupApp,TempAnalysis,UpdateStatus} from "./types";

const isTauri=()=>"__TAURI_INTERNALS__" in window;
const mock:Dashboard={pcName:"SETWELL-PC",windowsVersion:"Microsoft Windows 11 Pro",uptimeSeconds:19342,cpuUsage:18,memoryUsage:47,memoryUsedGb:7.5,memoryTotalGb:16,disks:[{name:"System",mount:"C:\\",usedGb:176,totalGb:237,usage:74}],network:{receivedMb:1240,transmittedMb:236,activeConnections:42,listeningPorts:11},healthScore:92,securityScore:88};
export async function call<T>(cmd:string,args:Record<string,unknown>={}):Promise<T>{
 if(isTauri())return invoke<T>(cmd,args);
 await new Promise(r=>setTimeout(r,280));
 const data:Record<string,unknown>={get_dashboard:mock,get_processes:[{pid:6404,name:"chrome.exe",cpu:8.4,memoryMb:684},{pid:1120,name:"explorer.exe",cpu:2.1,memoryMb:188},{pid:9232,name:"Code.exe",cpu:1.8,memoryMb:512}],get_network_connections:[{protocol:"TCP",localAddress:"192.168.1.8:52144",remoteAddress:"142.250.185.78:443",state:"Established",pid:6404,process:"chrome"},{protocol:"UDP",localAddress:"0.0.0.0:5353",remoteAddress:"*:*",state:"Bound",pid:1120,process:"svchost"}],get_security_status:{score:88,defenderEnabled:true,realTimeProtection:true,firewallEnabled:true,updateServiceRunning:false,updateServiceEnabled:true,issues:[]},list_activity:[{id:1,timestamp:new Date().toISOString(),action:"System snapshot",status:"success",detail:"Health 92 · Security 88"}],get_startup_apps:[{name:"OneDrive",command:"OneDrive.exe /background",location:"HKCU Run",user:"AK"}],get_services:[{name:"Spooler",displayName:"Print Spooler",status:"Running",startType:"Auto"}],get_installed_apps:[{name:"Microsoft Edge",version:"128.0",publisher:"Microsoft Corporation",source:"registry"},{name:"Zoom Workplace",version:"6.4",publisher:"Zoom Communications",source:"registry"}],get_network_config:{localIps:["192.168.1.8"],gateways:["192.168.1.1"],dnsServers:["1.1.1.1","8.8.8.8"],adapters:[{name:"Wi-Fi",description:"Wireless adapter",status:"Up",linkSpeed:"866 Mbps"}]},get_update_status:{serviceRunning:false,serviceEnabled:true,lastHotfixDate:new Date().toISOString(),lastHotfixId:"KB5060000",rebootPending:false},get_event_summary:{criticalCount24h:0,errorCount24h:2,recentCrashes:[]},analyze_temp_files:{path:"C:\\Users\\AK\\AppData\\Local\\Temp",totalBytes:1280000000,eligibleBytes:740000000,fileCount:4200,eligibleFileCount:3100},get_printers:[],get_physical_disks:[{name:"NVMe SSD",healthStatus:"Healthy",operationalStatus:"OK",mediaType:"SSD",temperatureC:42,wearPercent:2}],get_network_alerts:[],get_ai_usage:{inputTokens:0,outputTokens:0},get_runtime_status:{dryRun:true,elevated:false,aiConfigured:false,aiModel:"gpt-5.4-mini",wingetAvailable:true,wingetVersion:"preview"}};
 if(cmd==="assistant_message")return {message:"Kompyuter holatini lokal tekshiraman: CPU, RAM, disk, Windows xavfsizligi va tarmoq ulanishlari jamlanadi.",suggestedAction:{tool:"run_diagnostic",arguments:{type:"SYSTEM_CHECK"}},provider:"Local diagnostic"} as T;
 if(cmd==="search_apps")return [{name:"Zoom Workplace",id:"Zoom.Zoom",version:"6.4.0",source:"winget"}] as T;
 if(cmd==="propose_action")return {confirmationId:"demo",tool:"install_app",title:"Ilovani o‘rnatish",description:"Tasdiqlangan winget paketini o‘rnatadi.",riskLevel:2,requiresConfirmation:true,expiresAt:new Date(Date.now()+300000).toISOString()} as T;
 if(cmd==="execute_action")return {success:true,message:"DRY RUN: winget install --id Zoom.Zoom --exact",data:{},dryRun:true} as T;
 if(cmd==="run_diagnostic")return {diagnostic:(args.kind as string)||"SYSTEM_CHECK",score:82,summary:"2 ta e’tibor talab qiladigan holat topildi.",findings:[{code:"LOW_DISK_SPACE",severity:"medium",title:"Diskda bo‘sh joy kam",detail:"C:\\ diski 91% to‘lgan.",evidence:{}},{code:"TEMP_FILES_LARGE",severity:"low",title:"Temp fayllar",detail:"0.7 GB xavfsiz tozalanishi mumkin.",evidence:{}}],recommendedActions:["clear_temp_files"],collectedAt:new Date().toISOString()} as T;
 return data[cmd] as T;
}
export const api={dashboard:()=>call<Dashboard>("get_dashboard"),processes:()=>call<Process[]>("get_processes"),network:()=>call<Connection[]>("get_network_connections"),security:()=>call<Security>("get_security_status"),activities:()=>call<Activity[]>("list_activity",{limit:50}),startups:()=>call<StartupApp[]>("get_startup_apps"),services:()=>call<ServiceInfo[]>("get_services"),installed:()=>call<InstalledApp[]>("get_installed_apps"),networkConfig:()=>call<NetworkConfig>("get_network_config"),updateStatus:()=>call<UpdateStatus>("get_update_status"),events:()=>call<EventSummary>("get_event_summary"),temp:()=>call<TempAnalysis>("analyze_temp_files"),printers:()=>call<PrinterInfo[]>("get_printers"),physicalDisks:()=>call<PhysicalDiskHealth[]>("get_physical_disks"),networkAlerts:()=>call<NetworkAlert[]>("get_network_alerts"),diagnostic:(kind:string)=>call<DiagnosticResult>("run_diagnostic",{kind}),search:(query:string)=>call<Package[]>("search_apps",{query}),chat:(message:string)=>call<AssistantReply>("assistant_message",{message}),propose:(tool:string,arguments_:Record<string,string>={})=>call<Proposal>("propose_action",{request:{tool,arguments:arguments_}}),execute:(confirmationId:string)=>call<{success:boolean;message:string;dryRun:boolean}>("execute_action",{confirmationId}),cancel:(confirmationId:string)=>call<boolean>("cancel_action",{confirmationId}),aiUsage:()=>call<{inputTokens:number;outputTokens:number}>("get_ai_usage"),runtime:()=>call<RuntimeStatus>("get_runtime_status")};
